### ISSUE TITLE
Add in support for Ledger Stax

### ISSUE THREAD

**Issue by k-thornton** [rainbow-me/browser-extension#1026]
Hey there!  I've been really enjoying the browser extension, but I wanted to highlight that it doesn't recognize the Ledger Stax in the WebHID connection dialog.  I'm pretty sure it's simply a matter of adding the Stax's [USB identifier](https://developers.ledger.com/docs/transport/usb-identifiers/) to the code where you open up the WebHID connection, and it'll just work from there.

**Comment by DanielSinclair** [comment]
@k-thornton We have since adopted the latest Ledger SDKs, so I believe our support for this should be ready to go. We will work on additional UI improvements as more Stax devices make their way out. Please give our v1.3.57 release a try when it is available shortly, and let me know if all works as expected!
