### ISSUE TITLE
[BUG] Cannot redefine property: ethereum

### ISSUE THREAD

**Issue by AtelyPham** [rainbow-me/browser-extension#1560]
### Describe the bug
When Rainbow Wallet is installed along with other injected wallets (e.g. Metamask, Talisman, SubWallet), I got the `Cannot redefine property: ethereum` on the browser console, which makes the `window.ethereum.isRainbow === undefined` I believed. 

### To Reproduce
1. Installing Metamask, Talisman, SubWallet, and Rainbow browser extensions.
2. Go to https://www.rainbowkit.com/docs/connect-button
3. Open the browser console
4. You will see the error

### Expected behavior
The re-definition of `window.ethereum` should not throw an error.

### Screenshots

![CleanShot 2024-06-05 at 10 51 24@2x](https://github.com/rainbow-me/browser-extension/assets/60747384/84176f5a-a594-4c3e-8ac9-81ea60368749)

### Environment

 - OS: macOS
 - Browser: Chrome `v125.0.6422.113 (Official Build) (arm64)`
 - Rainbow browser extension `v1.4.111`

### Additional context

When I click on the error, it takes me to this line in the code:

<img alt="CleanShot 2024-06-05 at 10 56 07@2x" src="https://github.com/rainbow-me/browser-extension/assets/60747384/8d3fa29f-3147-4f76-851b-a647f69a4c5b" width="512" />

which on the source code, I think it is on this line: https://github.com/rainbow-me/browser-extension/blob/3d2557372813e905f0bfa3e9e69d50bc1e8c15b4/src/entries/inpage/index.ts#L101.

**Comment by DanielSinclair** [comment]
@AtelyPham I believe this might be an issue in Talisman or SubWallet. Wallets each inject their inpage script into the window for their Ethereum provider by overriding `window.ethereum`. Most place nice and replace `window.etherum` with their provider or determined by user preference and then add additional wallet providers as a list in `window.ethereum.providers`. Though some try to prevent other wallets from overriding `window.ethereum`, which triggers this error. It can be hard to tell because the order in which the page scripts are injected is not deterministic. Can you try to disable one or both of those to determine the culprit?

**Comment by AtelyPham** [comment]
You are right 👍 When I disabled Talisman and SubWallet, everything worked fine.

**Comment by AtelyPham** [comment]
On my dApp, I don't use Talisman and SubWallet for EVM chains, but I cannot find any way to opt out of EVM on these wallets. Do you have any suggestions?

**Comment by DanielSinclair** [comment]
@AtelyPham That would be a wallet specific issue. If they cause issue, it is usually the best practice to disable other wallet extensions via your browser settings and refresh the page to properly settle the injected connector. It can be a pain to do this, so I would recommend relaying this issue to those wallet teams.
